"""A-Priori CLI entry point (arch:core-lib-thin-shells).

Usage::

    apriori init [--repo PATH] [--no-embed]
    apriori search QUERY [--limit N] [--db PATH] [--json]
    apriori status [--db PATH] [--json]
    apriori rebuild-index [--db PATH] [--yaml-path PATH] [--no-embed]
    apriori config [set KEY VALUE] [--json]
    apriori ui [--host HOST] [--port PORT] [--db PATH] [--reload]

The ``init`` command initialises a repository for A-Priori:
  1. Creates ``.apriori/`` directory structure
  2. Writes a default ``apriori.config.yaml``
  3. Initialises DualWriter (SQLite + YAML)
  4. Runs the structural parser over all Python/TypeScript/JavaScript files
  5. Builds the knowledge graph (concept nodes + structural edges)
  6. Generates embeddings (unless ``--no-embed`` is passed)
  7. Prints a summary of what was discovered

The ``search`` subcommand queries the knowledge graph using FTS keyword search.
The ``status`` subcommand reports graph health metrics.
The ``ui`` subcommand launches the FastAPI server.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Default config template written on first init
# ---------------------------------------------------------------------------

_DEFAULT_CONFIG_TEMPLATE = """\
# A-Priori configuration — generated by `apriori init`
# Edit this file to customise your knowledge graph settings.
# Full schema: https://a-priori.dev/docs/configuration

storage:
  sqlite_path: "{apriori_dir}/graph.db"
  yaml_backup_path: "{apriori_dir}/concepts"
  enable_dual_write: true

embedding:
  model: "intfloat/e5-base-v2"
  dimensions: 768
  batch_size: 32

log_level: "INFO"
"""


# ---------------------------------------------------------------------------
# init command
# ---------------------------------------------------------------------------


def _cmd_init(args: argparse.Namespace) -> None:
    """Initialise A-Priori for a repository (thin shell, arch:core-lib-thin-shells)."""
    repo_path = Path(args.repo).resolve() if args.repo else Path.cwd().resolve()
    apriori_dir = repo_path / ".apriori"
    config_path = apriori_dir / "apriori.config.yaml"

    is_incremental = apriori_dir.exists()

    if is_incremental:
        print(f"A-Priori: incremental update for {repo_path}")
    else:
        print(f"A-Priori: initialising repository at {repo_path}")

    # ------------------------------------------------------------------
    # Step 1 — Create .apriori/ directory structure
    # ------------------------------------------------------------------
    apriori_dir.mkdir(parents=True, exist_ok=True)
    (apriori_dir / "concepts").mkdir(exist_ok=True)

    # ------------------------------------------------------------------
    # Step 2 — Write default config (only on first init)
    # ------------------------------------------------------------------
    if not is_incremental:
        config_content = _DEFAULT_CONFIG_TEMPLATE.format(
            apriori_dir=str(apriori_dir)
        )
        config_path.write_text(config_content)
        print(f"  Written config: {config_path}")

    # ------------------------------------------------------------------
    # Step 3 — Load config (reads the file we just created or an existing one)
    # ------------------------------------------------------------------
    from apriori.config import load_config

    config = load_config(config_path)

    # ------------------------------------------------------------------
    # Step 4 — Initialise storage (SQLite + YAML via DualWriter)
    # ------------------------------------------------------------------
    from apriori.storage.dual_writer import DualWriter
    from apriori.storage.sqlite_store import SQLiteStore
    from apriori.storage.yaml_store import YamlStore

    db_path = Path(config.storage.sqlite_path)
    yaml_path = Path(config.storage.yaml_backup_path)

    db_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.mkdir(parents=True, exist_ok=True)

    sqlite_store = SQLiteStore(db_path)
    yaml_store = YamlStore(yaml_path)
    store = DualWriter(sqlite_store=sqlite_store, yaml_store=yaml_store)

    # ------------------------------------------------------------------
    # Step 5 — Run structural parser over the repository
    # ------------------------------------------------------------------
    from apriori.structural.graph_builder import GraphBuilder
    from apriori.structural.languages.python_parser import PythonParser
    from apriori.structural.languages.typescript import TypeScriptParser
    from apriori.structural.models import ParseResult
    from apriori.structural.orchestrator import Orchestrator

    print(f"  Scanning {repo_path} for source files…")
    t0 = time.monotonic()

    orchestrator = Orchestrator()
    py_parser = PythonParser()
    ts_parser = TypeScriptParser()
    parse_results: list[ParseResult] = []
    file_count = 0

    for file_path, language, _raw_result in orchestrator.walk_and_parse(repo_path):
        # The Orchestrator returns raw tree-sitter results without extracted
        # entities.  Run the language-specific parser to populate functions,
        # classes, imports, and relationships.
        try:
            source = file_path.read_bytes()
            if language == "python":
                parse_result = py_parser.parse(source, file_path)
            else:
                # TypeScript, TSX, JavaScript all use the TypeScript parser
                parse_result = ts_parser.parse(source, file_path)
        except Exception:
            # Corrupt or unreadable file — skip silently (already logged by orchestrator)
            continue
        parse_results.append(parse_result)
        file_count += 1

    parse_elapsed = time.monotonic() - t0
    print(f"  Parsed {file_count} file(s) in {parse_elapsed:.1f}s")

    # ------------------------------------------------------------------
    # Step 6 — Detect git HEAD for provenance stamping (optional)
    # ------------------------------------------------------------------
    git_head = _get_git_head(repo_path)

    # ------------------------------------------------------------------
    # Step 7 — Build the knowledge graph (concepts + edges)
    # ------------------------------------------------------------------
    builder = GraphBuilder(store=store, git_head=git_head)
    build_result = builder.build(parse_results)

    print(
        f"  Graph: {build_result.concepts_created} concept(s) created, "
        f"{build_result.concepts_updated} updated, "
        f"{build_result.edges_created} edge(s) created"
    )

    # ------------------------------------------------------------------
    # Step 8 — Generate embeddings (unless --no-embed is passed)
    # ------------------------------------------------------------------
    no_embed = getattr(args, "no_embed", False)
    if not no_embed and (build_result.concepts_created + build_result.concepts_updated) > 0:
        from apriori.embedding.service import EmbeddingService

        print("  Loading embedding model (first run downloads ~440MB, cached after)…")
        svc = EmbeddingService()
        svc.embed_all(store)

    # ------------------------------------------------------------------
    # Step 9 — Print final summary
    # ------------------------------------------------------------------
    total_concepts = len(store.list_concepts())
    total_edges = len(store.list_edges())
    total_elapsed = time.monotonic() - t0

    print()
    if is_incremental:
        print("A-Priori incremental update complete.")
    else:
        print("A-Priori initialisation complete.")
    print(f"  Total concepts: {total_concepts}")
    print(f"  Total edges:    {total_edges}")
    print(f"  Elapsed:        {total_elapsed:.1f}s (excluding model download)")
    print()
    print("Next steps:")
    print("  apriori search '<query>'   — search the knowledge graph")
    print("  apriori status             — view graph health metrics")
    print("  apriori ui                 — start the Graph API server")


def _get_git_head(repo_path: Path) -> str | None:
    """Return the current git HEAD SHA, or None if not a git repo."""
    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(repo_path),
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# Helpers shared by search/status commands
# ---------------------------------------------------------------------------


def _resolve_db_path(args: argparse.Namespace) -> Path:
    """Determine the SQLite database path from args, config, or defaults.

    Resolution order:
    1. Explicit ``--db`` argument.
    2. Config file found at ``.apriori/apriori.config.yaml``.
    3. Fallback: ``.apriori/graph.db``.
    """
    if args.db:
        return Path(args.db)

    from apriori.config import load_config

    apriori_config = Path.cwd() / ".apriori" / "apriori.config.yaml"
    if apriori_config.exists():
        config = load_config(apriori_config)
    else:
        config = load_config()
    return Path(config.storage.sqlite_path)


# ---------------------------------------------------------------------------
# search command
# ---------------------------------------------------------------------------


def _cmd_search(args: argparse.Namespace) -> None:
    """Search the knowledge graph using FTS keyword matching."""
    import json as _json

    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)
    query = args.query
    limit = getattr(args, "limit", 10)
    use_json = getattr(args, "json", False)

    results = store.search_keyword(query, limit=limit)

    if use_json:
        output = [
            {
                "name": c.name,
                "description": c.description,
                "confidence": c.confidence,
                "labels": sorted(c.labels),
            }
            for c in results
        ]
        print(_json.dumps(output))
        return

    if not results:
        print(f"No results for '{query}'.")
        return

    print(f"Results for '{query}' ({len(results)} match(es)):\n")
    for i, concept in enumerate(results, start=1):
        desc = concept.description or ""
        if len(desc) > 100:
            desc = desc[:97] + "…"
        print(f"  {i}. {concept.name}  conf: {concept.confidence:.2f}")
        if desc:
            print(f"     {desc}")
    print()


# ---------------------------------------------------------------------------
# status command
# ---------------------------------------------------------------------------


def _cmd_status(args: argparse.Namespace) -> None:
    """Report knowledge graph health metrics."""
    import json as _json

    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)
    use_json = getattr(args, "json", False)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)

    metrics = store.get_metrics()
    concept_count = metrics["concept_count"]
    edge_count = metrics["edge_count"]

    covered_files = store.count_covered_files()
    pending_items = store.get_pending_work_items()
    work_queue_depth = len(pending_items)

    last_parse: str | None = store.get_last_parse_timestamp()

    if use_json:
        print(_json.dumps({
            "concept_count": concept_count,
            "edge_count": edge_count,
            "covered_files": covered_files,
            "work_queue_depth": work_queue_depth,
            "last_parse": last_parse,
            "database": str(db_path.resolve()),
        }))
        return

    print("A-Priori Graph Status")
    print("=" * 40)
    print(f"  Concepts:          {concept_count}")
    print(f"  Edges:             {edge_count}")
    print(f"  Covered files:     {covered_files}")
    print(f"  Work queue depth:  {work_queue_depth}")
    print(f"  Last parse:        {last_parse or 'n/a'}")
    print(f"  Database:          {db_path.resolve()}")
    print()


# ---------------------------------------------------------------------------
# rebuild-index command
# ---------------------------------------------------------------------------


def _cmd_rebuild_index(args: argparse.Namespace) -> None:
    """Reconstruct the SQLite database from YAML flat files (arch:core-lib-thin-shells)."""
    from apriori.config import load_config
    from apriori.embedding.service import EmbeddingService
    from apriori.storage.rebuild import rebuild_index_from_yaml
    from apriori.storage.yaml_store import YamlStore

    apriori_config_path = Path.cwd() / ".apriori" / "apriori.config.yaml"
    config = load_config(apriori_config_path if apriori_config_path.exists() else None)

    db_path = Path(args.db) if getattr(args, "db", None) else Path(config.storage.sqlite_path)
    yaml_base = Path(args.yaml_path) if getattr(args, "yaml_path", None) else Path(config.storage.yaml_backup_path)

    yaml_store = YamlStore(yaml_base)

    no_embed = getattr(args, "no_embed", False)

    print(f"Rebuilding index from YAML files at {yaml_base}…")
    print(f"  Target database: {db_path.resolve()}")

    if no_embed:
        class _NullEmbeddingService:
            def generate_embedding(self, text: str, **kw: object) -> list[float]:
                return [0.0] * 768

            def generate_embeddings_batch(self, texts: list[str], **kw: object) -> list[list[float]]:
                return [[0.0] * 768 for _ in texts]

        embedding_svc: object = _NullEmbeddingService()
    else:
        print("  Loading embedding model…")
        embedding_svc = EmbeddingService()

    def _progress(current: int, total: int, message: str) -> None:
        if total > 0:
            print(f"  [{current}/{total}] {message}")
        else:
            print(f"  {message}")

    rebuild_index_from_yaml(
        yaml_store,
        db_path=db_path,
        embedding_service=embedding_svc,
        progress_callback=_progress,
    )

    print()
    print("Rebuild complete.")


# ---------------------------------------------------------------------------
# config command
# ---------------------------------------------------------------------------


def _resolve_config_path() -> Path:
    """Return the config file path, preferring .apriori/ in the current directory."""
    candidate = Path.cwd() / ".apriori" / "apriori.config.yaml"
    if candidate.exists():
        return candidate
    return candidate  # Return even if not existing so callers can create it


def _cmd_config(args: argparse.Namespace) -> None:
    """Show or modify A-Priori configuration (arch:core-lib-thin-shells)."""
    import json as _json

    from apriori.config import load_config

    config_subcommand = getattr(args, "config_subcommand", None)
    use_json = getattr(args, "json", False)

    if config_subcommand == "set":
        _config_set(args)
        return

    # Default: print effective configuration
    config_path = _resolve_config_path()
    config = load_config(config_path if config_path.exists() else None)

    if use_json:
        print(_json.dumps(config.model_dump(mode="json"), indent=2, default=str))
        return

    print(f"A-Priori Configuration  (source: {config_path})")
    print("=" * 50)
    data = config.model_dump(mode="json")
    _print_config_section(data, indent=0)
    print()


def _print_config_section(data: dict, indent: int) -> None:
    """Recursively print config dict in aligned text format."""
    prefix = "  " * indent
    for key, value in sorted(data.items()):
        if isinstance(value, dict):
            print(f"{prefix}{key}:")
            _print_config_section(value, indent + 1)
        elif isinstance(value, (list, set)):
            display = ", ".join(str(v) for v in sorted(str(x) for x in value))
            print(f"{prefix}{key}: [{display}]")
        else:
            print(f"{prefix}{key}: {value}")


def _config_set(args: argparse.Namespace) -> None:
    """Update a single key in the config file using dotted notation."""
    import yaml as _yaml

    key: str = args.key
    raw_value: str = args.value

    config_path = _resolve_config_path()

    # Load existing raw YAML (preserve structure; don't parse through Config)
    existing: dict = {}
    if config_path.exists():
        loaded = _yaml.safe_load(config_path.read_text())
        if loaded:
            existing = loaded

    # Parse the dotted key into nested path
    parts = key.split(".")
    # Navigate to the nested position, creating dicts as needed
    node = existing
    for part in parts[:-1]:
        if part not in node or not isinstance(node[part], dict):
            node[part] = {}
        node = node[part]

    leaf_key = parts[-1]
    # Coerce value type: try int, then float, then bool, then string
    coerced: object = raw_value
    if raw_value.lower() in ("true", "false"):
        coerced = raw_value.lower() == "true"
    else:
        try:
            coerced = int(raw_value)
        except ValueError:
            try:
                coerced = float(raw_value)
            except ValueError:
                coerced = raw_value  # Keep as string

    node[leaf_key] = coerced

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_yaml.dump(existing, allow_unicode=True, sort_keys=True))
    print(f"Updated {key} = {coerced!r}  (saved to {config_path})")


# ---------------------------------------------------------------------------
# ui command
# ---------------------------------------------------------------------------


def _cmd_ui(args: argparse.Namespace) -> None:
    """Start the read-only Graph API server."""
    try:
        import uvicorn
    except ImportError:
        print(
            "Error: uvicorn is required to run the UI server.\n"
            "Install it with: pip install uvicorn",
            file=sys.stderr,
        )
        sys.exit(1)

    from apriori.config import load_config
    from apriori.shells.ui.server import create_app
    from apriori.storage.dual_writer import DualWriter
    from apriori.storage.sqlite_store import SQLiteStore
    from apriori.storage.yaml_store import YamlStore

    config = load_config()

    db_path = Path(args.db) if args.db else Path(config.storage.sqlite_path)
    yaml_path = Path(config.storage.yaml_backup_path)

    sqlite_store = SQLiteStore(db_path)
    if config.storage.enable_dual_write:
        yaml_store = YamlStore(yaml_path)
        store = DualWriter(sqlite_store=sqlite_store, yaml_store=yaml_store)
    else:
        store = sqlite_store  # type: ignore[assignment]

    app = create_app(store, config)

    print(f"Starting A-Priori UI server on http://{args.host}:{args.port}")
    print(f"Database: {db_path.resolve()}")
    print("API docs: http://{}:{}/docs".format(args.host, args.port))

    uvicorn.run(app, host=args.host, port=args.port, reload=args.reload)


# ---------------------------------------------------------------------------
# blast-radius command
# ---------------------------------------------------------------------------


def _cmd_blast_radius(args: argparse.Namespace) -> None:
    """Display the pre-computed blast-radius impact profile for a target."""
    import json as _json

    from apriori.retrieval.blast_radius_query import query_blast_radius
    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)
    use_json = getattr(args, "json", False)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)
    target = args.target
    max_depth = getattr(args, "depth", None)
    min_confidence = getattr(args, "min_confidence", None)

    entries = query_blast_radius(store, target, max_depth=max_depth, min_confidence=min_confidence)

    if use_json:
        print(_json.dumps(
            [
                {
                    "concept_id": str(e.concept_id),
                    "concept_name": e.concept_name,
                    "confidence": e.confidence,
                    "impact_layer": e.impact_layer,
                    "depth": e.depth,
                    "relationship_path": e.relationship_path,
                    "rationale": e.rationale,
                    "composite_score": e.composite_score,
                }
                for e in entries
            ]
        ))
        return

    if not entries:
        print(f"No blast-radius impact found for '{target}'.")
        return

    print(f"Blast-radius impact for '{target}' ({len(entries)} entry/entries):\n")
    for i, entry in enumerate(entries, start=1):
        print(
            f"  {i}. {entry.concept_name}"
            f"  layer={entry.impact_layer}"
            f"  depth={entry.depth}"
            f"  confidence={entry.confidence:.2f}"
            f"  score={entry.composite_score:.3f}"
        )
        print(f"     {entry.rationale}")
    print()


# ---------------------------------------------------------------------------
# Shared helpers for new commands
# ---------------------------------------------------------------------------


def _build_store_from_args(args: argparse.Namespace):
    """Build a KnowledgeStore from CLI args (SQLiteStore, arch:core-lib-thin-shells)."""
    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)
    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)
    return SQLiteStore(db_path)


def _build_adapter_from_config(config):
    """Build an LLM adapter from config (arch:adapter-pattern)."""
    if config.llm.provider == "ollama":
        from apriori.adapters.ollama import OllamaAdapter
        return OllamaAdapter(config.llm)
    from apriori.adapters.anthropic import AnthropicAdapter
    return AnthropicAdapter(config.llm)


def _resolve_yaml_backup_path(args: argparse.Namespace) -> Path:
    """Return the YAML backup directory path from args or config."""
    from apriori.config import load_config

    apriori_config = Path.cwd() / ".apriori" / "apriori.config.yaml"
    if apriori_config.exists():
        config = load_config(apriori_config)
    else:
        config = load_config()
    yaml_path = Path(config.storage.yaml_backup_path)
    if yaml_path.is_dir() and (yaml_path / "concepts").is_dir():
        return yaml_path / "concepts"
    return yaml_path


# ---------------------------------------------------------------------------
# librarian run command
# ---------------------------------------------------------------------------


def _cmd_librarian_run(args: argparse.Namespace) -> None:
    """Execute the librarian loop for up to --iterations iterations
    within an optional token --budget (arch:core-lib-thin-shells)."""
    import asyncio

    from apriori.config import load_config
    from apriori.librarian.loop import LibrarianLoop
    from apriori.storage.dual_writer import DualWriter
    from apriori.storage.sqlite_store import SQLiteStore
    from apriori.storage.yaml_store import YamlStore

    apriori_config = Path.cwd() / ".apriori" / "apriori.config.yaml"
    config = load_config(apriori_config if apriori_config.exists() else None)

    budget = getattr(args, "budget", None)
    if budget is not None:
        config = config.model_copy(
            update={"budget": config.budget.model_copy(update={"max_tokens_per_run": budget})}
        )

    iterations = getattr(args, "iterations", None) or config.librarian.max_iterations_per_run

    # Build store with dual-write support for write operations (arch:sqlite-vec-storage).
    # Use one store without the other only for read-only commands.
    db_path = _resolve_db_path(args)
    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    sqlite_store = SQLiteStore(db_path)
    if config.storage.enable_dual_write:
        yaml_path = Path(config.storage.yaml_backup_path)
        yaml_store = YamlStore(yaml_path)
        store = DualWriter(sqlite_store=sqlite_store, yaml_store=yaml_store)
    else:
        store = sqlite_store  # type: ignore[assignment]

    adapter = _build_adapter_from_config(config)

    loop = LibrarianLoop(store=store, adapter=adapter, config=config)

    print(f"Running librarian loop: up to {iterations} iteration(s)…")
    if budget:
        print(f"  Token budget: {budget:,}")

    activities, telemetry = asyncio.run(loop.run(iterations))

    print()
    print("Librarian run complete.")
    print(f"  Iterations:       {telemetry.total_iterations}")
    print(f"  Tokens used:      {telemetry.total_tokens:,}")
    print(f"  Yield:            {telemetry.iteration_yield:.1%}")
    print(f"  Items resolved:   {telemetry.work_items_resolved}")
    print(f"  Items failed:     {telemetry.work_items_failed}")
    print(f"  Concepts created: {telemetry.concepts_created}")
    print(f"  Edges created:    {telemetry.edges_created}")
    print()


# ---------------------------------------------------------------------------
# librarian status command
# ---------------------------------------------------------------------------


def _cmd_librarian_status(args: argparse.Namespace) -> None:
    """Display detailed iteration yield, token spend history, and failure
    logs for the last 5 librarian runs."""
    import json as _json
    from collections import defaultdict

    use_json = getattr(args, "json", False)
    store = _build_store_from_args(args)

    activities = store.list_librarian_activities()

    if not activities:
        if use_json:
            print(_json.dumps([]))
        else:
            print("No librarian runs recorded yet.")
            print("Run `apriori librarian run` to start the librarian.")
        return

    # Group by run_id, preserving insertion order (activities sorted by iteration)
    runs: dict = defaultdict(list)
    for act in activities:
        runs[str(act.run_id)].append(act)

    # Sort runs by the created_at of their first activity (most recent last)
    sorted_run_ids = sorted(
        runs.keys(),
        key=lambda rid: runs[rid][0].created_at,
    )

    if use_json:
        output = []
        for rid in sorted_run_ids:
            run_acts = runs[rid]
            total = len(run_acts)
            resolved = sum(1 for a in run_acts if a.status == "success")
            total_tokens = sum(a.tokens_used for a in run_acts)
            failures = [
                {"iteration": a.iteration, "status": a.status, "reason": a.failure_reason}
                for a in run_acts
                if a.failure_reason
            ]
            output.append({
                "run_id": rid,
                "total_iterations": total,
                "resolved": resolved,
                "yield": resolved / total if total else 0.0,
                "total_tokens": total_tokens,
                "failures": failures,
            })
        print(_json.dumps(output))
        return

    print("Librarian Run History")
    print("=" * 60)

    # Show last 5 runs (most recent at the bottom)
    last_5_ids = sorted_run_ids[-5:]
    for rid in last_5_ids:
        run_acts = runs[rid]
        total = len(run_acts)
        resolved = sum(1 for a in run_acts if a.status == "success")
        run_yield = resolved / total if total else 0.0
        total_tokens = sum(a.tokens_used for a in run_acts)
        started_at = run_acts[0].created_at.strftime("%Y-%m-%d %H:%M:%S UTC")
        print(f"\n  Run {rid[:8]}…  ({started_at})")
        print(
            f"    Iterations: {total}  |  Yield: {run_yield:.1%}  |  "
            f"Resolved: {resolved}  |  Tokens: {total_tokens:,}"
        )

        failures = [a for a in run_acts if a.failure_reason]
        if failures:
            print("    Failures:")
            for a in failures:
                print(f"      [iter {a.iteration}] {a.status}: {a.failure_reason}")

    print()


# ---------------------------------------------------------------------------
# concept command
# ---------------------------------------------------------------------------


def _cmd_concept(args: argparse.Namespace) -> None:
    """Display full details for a concept by name (arch:core-lib-thin-shells)."""
    import json as _json

    name: str = args.name
    use_json = getattr(args, "json", False)
    store = _build_store_from_args(args)

    results = store.search_keyword(name, limit=20)

    # Prefer exact name match; fall back to first result
    exact = [c for c in results if c.name.lower() == name.lower()]
    candidates = exact if exact else results

    if use_json:
        print(_json.dumps(
            [c.model_dump(mode="json") for c in candidates],
            default=str,
        ))
        return

    if not candidates:
        print(f"Concept '{name}' not found.")
        print("Try `apriori search <query>` for fuzzy matches.")
        return

    for concept in candidates:
        print()
        print(f"  Name:        {concept.name}")
        print(f"  ID:          {concept.id}")
        print(f"  Confidence:  {concept.confidence:.2f}")
        print(f"  Labels:      {', '.join(sorted(concept.labels)) or 'none'}")
        print(f"  Description: {concept.description or '(none)'}")
        if concept.code_references:
            print("  Code References:")
            for ref in concept.code_references:
                loc = f":{ref.line_range[0]}-{ref.line_range[1]}" if ref.line_range else ""
                print(f"    • {ref.file_path}{loc}  [{ref.symbol}]")
        if concept.created_at:
            print(f"  Created:     {concept.created_at}")
        if concept.updated_at:
            print(f"  Updated:     {concept.updated_at}")
        print()


# ---------------------------------------------------------------------------
# validate command
# ---------------------------------------------------------------------------


def _cmd_validate(args: argparse.Namespace) -> None:
    """Run integrity checks on the knowledge graph
    (arch:core-lib-thin-shells)."""
    import json as _json

    use_json = getattr(args, "json", False)
    store = _build_store_from_args(args)

    errors: list[str] = []

    # ------------------------------------------------------------------
    # Check 1: All edge references point to existing concepts
    # ------------------------------------------------------------------
    concepts = store.list_concepts()
    concept_ids = {c.id for c in concepts}
    edges = store.list_edges()

    for edge in edges:
        if edge.source_id not in concept_ids:
            errors.append(
                f"Dangling edge {edge.id}: source concept {edge.source_id} not found"
            )
        if edge.target_id not in concept_ids:
            errors.append(
                f"Dangling edge {edge.id}: target concept {edge.target_id} not found"
            )

    # ------------------------------------------------------------------
    # Check 2: All code references have valid file paths
    # ------------------------------------------------------------------
    for concept in concepts:
        for ref in concept.code_references:
            if ref.is_unresolved:
                continue  # already marked unresolved — skip
            p = Path(ref.file_path)
            if not p.is_absolute():
                continue  # relative paths cannot be validated without repo root
            if not p.exists():
                errors.append(
                    f"Concept '{concept.name}': code reference file not found: {ref.file_path}"
                )

    # ------------------------------------------------------------------
    # Check 3: No orphaned YAML files (YAML concept not in SQLite)
    # ------------------------------------------------------------------
    yaml_path = _resolve_yaml_backup_path(args)
    if yaml_path.is_dir():
        import yaml as _yaml

        sqlite_ids = concept_ids
        for yaml_file in sorted(yaml_path.glob("*.yaml")):
            try:
                data = _yaml.safe_load(yaml_file.read_text())
            except Exception:
                errors.append(f"Orphaned/corrupt YAML file: {yaml_file.name}")
                continue
            if not data or "id" not in data:
                errors.append(f"YAML file missing 'id' field: {yaml_file.name}")
                continue
            try:
                import uuid as _uuid
                yaml_id = _uuid.UUID(str(data["id"]))
            except ValueError:
                errors.append(f"YAML file has invalid UUID 'id': {yaml_file.name}")
                continue
            if yaml_id not in sqlite_ids:
                errors.append(
                    f"Orphaned YAML concept '{data.get('name', yaml_file.stem)}' "
                    f"({yaml_file.name}) not found in SQLite"
                )

    if use_json:
        print(_json.dumps({"errors": errors}))
        return

    if not errors:
        print("Validation OK — 0 errors found.")
    else:
        print(f"Validation found {len(errors)} error(s):")
        for err in errors:
            print(f"  [ERROR] {err}")
        sys.exit(1)


# ---------------------------------------------------------------------------
# export command
# ---------------------------------------------------------------------------


def _cmd_export(args: argparse.Namespace) -> None:
    """Export the full knowledge graph to a file or stdout
    (arch:core-lib-thin-shells)."""
    import json as _json

    fmt = getattr(args, "format", "json")
    output_path = getattr(args, "output", None)

    store = _build_store_from_args(args)

    concepts = store.list_concepts()
    edges = store.list_edges()

    if fmt == "json":
        payload = {
            "concepts": [c.model_dump(mode="json") for c in concepts],
            "edges": [e.model_dump(mode="json") for e in edges],
        }
        text = _json.dumps(payload, default=str, indent=2)
    else:
        print(f"Error: unsupported format '{fmt}'", file=sys.stderr)
        sys.exit(1)

    if output_path:
        Path(output_path).write_text(text)
        print(f"Exported {len(concepts)} concept(s) and {len(edges)} edge(s) to {output_path}")
    else:
        print(text)


# ---------------------------------------------------------------------------
# doctor — subsystem health check helpers
# ---------------------------------------------------------------------------


def _check_tree_sitter() -> tuple[bool, str]:
    """Check that tree-sitter is importable."""
    try:
        import tree_sitter  # noqa: F401
        return True, ""
    except ImportError:
        return False, "Install tree-sitter: pip install tree-sitter"


def _check_llm_connectivity(config) -> tuple[bool, str]:
    """Check that the LLM API key env variable is set."""
    import os

    key = os.environ.get(config.llm.api_key_env)
    if not key:
        return (
            False,
            f"Set ${config.llm.api_key_env} environment variable "
            f"(provider: {config.llm.provider})",
        )
    return True, ""


def _check_sqlite_health(args: argparse.Namespace) -> tuple[bool, str]:
    """Check that the SQLite database is accessible."""
    import sqlite3 as _sqlite3

    try:
        db_path = _resolve_db_path(args)
    except SystemExit:
        return False, "Could not determine database path — run `apriori init` first"
    if not db_path.exists():
        return False, f"Database not found at {db_path} — run `apriori init` first"
    try:
        with _sqlite3.connect(str(db_path)) as conn:
            conn.execute("SELECT 1")
        return True, ""
    except Exception as exc:
        return False, f"SQLite error: {exc}"


def _check_git_integration() -> tuple[bool, str]:
    """Check that git is available in PATH."""
    import subprocess

    try:
        result = subprocess.run(
            ["git", "--version"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return True, ""
        return False, "git returned non-zero exit code — ensure git is installed"
    except FileNotFoundError:
        return False, "git not found in PATH — install git"
    except Exception as exc:
        return False, f"git check failed: {exc}"


def _check_embedding_model() -> tuple[bool, str]:
    """Check that sentence-transformers is importable."""
    try:
        import sentence_transformers  # noqa: F401
        return True, ""
    except ImportError:
        return (
            False,
            "Install sentence-transformers: pip install sentence-transformers",
        )


def _cmd_doctor(args: argparse.Namespace) -> None:
    """Check all A-Priori subsystems and report pass/fail with guidance
    (arch:core-lib-thin-shells)."""
    from apriori.config import load_config

    apriori_config = Path.cwd() / ".apriori" / "apriori.config.yaml"
    config = load_config(apriori_config if apriori_config.exists() else None)

    checks: list[tuple[str, bool, str]] = [
        ("tree-sitter",        *_check_tree_sitter()),
        ("LLM connectivity",   *_check_llm_connectivity(config)),
        ("SQLite health",      *_check_sqlite_health(args)),
        ("git integration",    *_check_git_integration()),
        ("embedding model",    *_check_embedding_model()),
    ]

    any_fail = False
    print("A-Priori Doctor")
    print("=" * 50)
    for label, ok, guidance in checks:
        status = "PASS" if ok else "FAIL"
        line = f"  [{status}]  {label}"
        print(line)
        if not ok:
            any_fail = True
            print(f"         → {guidance}")
    print()

    if any_fail:
        print("Some checks failed. See guidance above.")
        sys.exit(1)
    else:
        print("All checks passed.")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    """Build and return the top-level argument parser for the apriori CLI."""
    parser = argparse.ArgumentParser(
        prog="apriori",
        description="A-Priori knowledge graph system",
    )
    subparsers = parser.add_subparsers(dest="command", metavar="COMMAND")

    # apriori init
    init_parser = subparsers.add_parser(
        "init",
        help="Initialise A-Priori for the current repository",
    )
    init_parser.add_argument(
        "--repo",
        default=None,
        metavar="PATH",
        help="Path to the repository root (default: current directory)",
    )
    init_parser.add_argument(
        "--no-embed",
        action="store_true",
        dest="no_embed",
        help="Skip embedding generation (faster, but semantic search will not work)",
    )

    # apriori search
    search_parser = subparsers.add_parser(
        "search",
        help="Search the knowledge graph",
    )
    search_parser.add_argument(
        "query",
        help="Search query",
    )
    search_parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Maximum number of results to return (default: 10)",
    )
    search_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    search_parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON",
    )

    # apriori status
    status_parser = subparsers.add_parser(
        "status",
        help="Show knowledge graph health metrics",
    )
    status_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    status_parser.add_argument(
        "--json",
        action="store_true",
        help="Output status as JSON",
    )

    # apriori rebuild-index
    rebuild_parser = subparsers.add_parser(
        "rebuild-index",
        help="Reconstruct the SQLite database from YAML flat files",
    )
    rebuild_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database to rebuild (default: from config or .apriori/graph.db)",
    )
    rebuild_parser.add_argument(
        "--yaml-path",
        default=None,
        metavar="PATH",
        dest="yaml_path",
        help="Path to YAML backup directory (default: from config or .apriori/concepts)",
    )
    rebuild_parser.add_argument(
        "--no-embed",
        action="store_true",
        dest="no_embed",
        help="Skip embedding regeneration (uses zero vectors)",
    )

    # apriori config
    config_parser = subparsers.add_parser(
        "config",
        help="View or modify A-Priori configuration",
    )
    config_parser.add_argument(
        "--json",
        action="store_true",
        help="Output configuration as JSON",
    )
    config_subparsers = config_parser.add_subparsers(
        dest="config_subcommand", metavar="SUBCOMMAND"
    )
    config_set_parser = config_subparsers.add_parser(
        "set",
        help="Set a configuration value (dotted key notation, e.g. librarian.max_iterations_per_run)",
    )
    config_set_parser.add_argument("key", help="Dotted key path (e.g. librarian.max_iterations_per_run)")
    config_set_parser.add_argument("value", help="New value")

    # apriori ui
    ui_parser = subparsers.add_parser(
        "ui",
        help="Start the read-only Graph API and dashboard server",
    )
    ui_parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="Host to bind the server to (default: 127.0.0.1)",
    )
    ui_parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to bind the server to (default: 8000)",
    )
    ui_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or ./apriori.db)",
    )
    ui_parser.add_argument(
        "--reload",
        action="store_true",
        help="Enable auto-reload on code changes (development only)",
    )

    # apriori blast-radius
    br_parser = subparsers.add_parser(
        "blast-radius",
        help="Show the pre-computed blast-radius impact profile for a target",
    )
    br_parser.add_argument(
        "target",
        help="Concept name, UUID, file path, or function symbol to query",
    )
    br_parser.add_argument(
        "--depth",
        type=int,
        default=None,
        metavar="N",
        help="Maximum hop depth to include (default: no limit)",
    )
    br_parser.add_argument(
        "--min-confidence",
        type=float,
        default=None,
        dest="min_confidence",
        metavar="FLOAT",
        help="Minimum confidence threshold (default: no limit)",
    )
    br_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    br_parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON",
    )

    # apriori librarian
    librarian_parser = subparsers.add_parser(
        "librarian",
        help="Manage the librarian loop (run, status)",
    )
    librarian_subparsers = librarian_parser.add_subparsers(
        dest="librarian_subcommand", metavar="SUBCOMMAND"
    )

    # apriori librarian run
    lib_run_parser = librarian_subparsers.add_parser(
        "run",
        help="Execute the librarian loop",
    )
    lib_run_parser.add_argument(
        "--iterations",
        type=int,
        default=None,
        metavar="N",
        help="Maximum iterations to run (default: from config)",
    )
    lib_run_parser.add_argument(
        "--budget",
        type=int,
        default=None,
        metavar="TOKENS",
        help="Token budget for this run (overrides config)",
    )
    lib_run_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )

    # apriori librarian status
    lib_status_parser = librarian_subparsers.add_parser(
        "status",
        help="Show detailed librarian run history",
    )
    lib_status_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    lib_status_parser.add_argument(
        "--json",
        action="store_true",
        help="Output status as JSON",
    )

    # apriori concept
    concept_parser = subparsers.add_parser(
        "concept",
        help="Display full details for a concept by name",
    )
    concept_parser.add_argument(
        "name",
        help="Concept name to look up",
    )
    concept_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    concept_parser.add_argument(
        "--json",
        action="store_true",
        help="Output concept details as JSON",
    )

    # apriori validate
    validate_parser = subparsers.add_parser(
        "validate",
        help="Run integrity checks on the knowledge graph",
    )
    validate_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    validate_parser.add_argument(
        "--json",
        action="store_true",
        help="Output validation results as JSON",
    )

    # apriori export
    export_parser = subparsers.add_parser(
        "export",
        help="Export the full knowledge graph",
    )
    export_parser.add_argument(
        "--format",
        choices=["json"],
        default="json",
        help="Export format (default: json)",
    )
    export_parser.add_argument(
        "--output",
        default=None,
        metavar="PATH",
        help="Output file path (default: stdout)",
    )
    export_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )

    # apriori doctor
    doctor_parser = subparsers.add_parser(
        "doctor",
        help="Check all A-Priori subsystems and report health",
    )
    doctor_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )

    return parser


def main() -> None:
    """Main CLI entry point for the ``apriori`` command."""
    parser = _build_parser()
    args = parser.parse_args()

    if args.command == "init":
        _cmd_init(args)
    elif args.command == "search":
        _cmd_search(args)
    elif args.command == "status":
        _cmd_status(args)
    elif args.command == "rebuild-index":
        _cmd_rebuild_index(args)
    elif args.command == "config":
        _cmd_config(args)
    elif args.command == "ui":
        _cmd_ui(args)
    elif args.command == "blast-radius":
        _cmd_blast_radius(args)
    elif args.command == "librarian":
        sub = getattr(args, "librarian_subcommand", None)
        if sub == "run":
            _cmd_librarian_run(args)
        elif sub == "status":
            _cmd_librarian_status(args)
        else:
            # Print librarian sub-help
            parser._subparsers._group_actions[0].choices["librarian"].print_help()
            sys.exit(0)
    elif args.command == "concept":
        _cmd_concept(args)
    elif args.command == "validate":
        _cmd_validate(args)
    elif args.command == "export":
        _cmd_export(args)
    elif args.command == "doctor":
        _cmd_doctor(args)
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
