"""A-Priori CLI entry point (arch:core-lib-thin-shells).

Usage::

    apriori init [--repo PATH] [--no-embed]
    apriori search QUERY [--limit N] [--db PATH] [--json]
    apriori status [--db PATH] [--json]
    apriori rebuild-index [--db PATH] [--yaml-path PATH] [--no-embed]
    apriori config [set KEY VALUE] [--json]
    apriori ui [--host HOST] [--port PORT] [--db PATH] [--reload]

The ``init`` command initialises a repository for A-Priori:
  1. Creates ``.apriori/`` directory structure
  2. Writes a default ``apriori.config.yaml``
  3. Initialises DualWriter (SQLite + YAML)
  4. Runs the structural parser over all Python/TypeScript/JavaScript files
  5. Builds the knowledge graph (concept nodes + structural edges)
  6. Generates embeddings (unless ``--no-embed`` is passed)
  7. Prints a summary of what was discovered

The ``search`` subcommand queries the knowledge graph using FTS keyword search.
The ``status`` subcommand reports graph health metrics.
The ``ui`` subcommand launches the FastAPI server.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Default config template written on first init
# ---------------------------------------------------------------------------

_DEFAULT_CONFIG_TEMPLATE = """\
# A-Priori configuration — generated by `apriori init`
# Edit this file to customise your knowledge graph settings.
# Full schema: https://a-priori.dev/docs/configuration

storage:
  sqlite_path: "{apriori_dir}/graph.db"
  yaml_backup_path: "{apriori_dir}/concepts"
  enable_dual_write: true

embedding:
  model: "intfloat/e5-base-v2"
  dimensions: 768
  batch_size: 32

log_level: "INFO"
"""


# ---------------------------------------------------------------------------
# init command
# ---------------------------------------------------------------------------


def _cmd_init(args: argparse.Namespace) -> None:
    """Initialise A-Priori for a repository (thin shell, arch:core-lib-thin-shells)."""
    repo_path = Path(args.repo).resolve() if args.repo else Path.cwd().resolve()
    apriori_dir = repo_path / ".apriori"
    config_path = apriori_dir / "apriori.config.yaml"

    is_incremental = apriori_dir.exists()

    if is_incremental:
        print(f"A-Priori: incremental update for {repo_path}")
    else:
        print(f"A-Priori: initialising repository at {repo_path}")

    # ------------------------------------------------------------------
    # Step 1 — Create .apriori/ directory structure
    # ------------------------------------------------------------------
    apriori_dir.mkdir(parents=True, exist_ok=True)
    (apriori_dir / "concepts").mkdir(exist_ok=True)

    # ------------------------------------------------------------------
    # Step 2 — Write default config (only on first init)
    # ------------------------------------------------------------------
    if not is_incremental:
        config_content = _DEFAULT_CONFIG_TEMPLATE.format(
            apriori_dir=str(apriori_dir)
        )
        config_path.write_text(config_content)
        print(f"  Written config: {config_path}")

    # ------------------------------------------------------------------
    # Step 3 — Load config (reads the file we just created or an existing one)
    # ------------------------------------------------------------------
    from apriori.config import load_config

    config = load_config(config_path)

    # ------------------------------------------------------------------
    # Step 4 — Initialise storage (SQLite + YAML via DualWriter)
    # ------------------------------------------------------------------
    from apriori.storage.dual_writer import DualWriter
    from apriori.storage.sqlite_store import SQLiteStore
    from apriori.storage.yaml_store import YamlStore

    db_path = Path(config.storage.sqlite_path)
    yaml_path = Path(config.storage.yaml_backup_path)

    db_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.mkdir(parents=True, exist_ok=True)

    sqlite_store = SQLiteStore(db_path)
    yaml_store = YamlStore(yaml_path)
    store = DualWriter(sqlite_store=sqlite_store, yaml_store=yaml_store)

    # ------------------------------------------------------------------
    # Step 5 — Run structural parser over the repository
    # ------------------------------------------------------------------
    from apriori.structural.graph_builder import GraphBuilder
    from apriori.structural.languages.python_parser import PythonParser
    from apriori.structural.languages.typescript import TypeScriptParser
    from apriori.structural.models import ParseResult
    from apriori.structural.orchestrator import Orchestrator

    print(f"  Scanning {repo_path} for source files…")
    t0 = time.monotonic()

    orchestrator = Orchestrator()
    py_parser = PythonParser()
    ts_parser = TypeScriptParser()
    parse_results: list[ParseResult] = []
    file_count = 0

    for file_path, language, _raw_result in orchestrator.walk_and_parse(repo_path):
        # The Orchestrator returns raw tree-sitter results without extracted
        # entities.  Run the language-specific parser to populate functions,
        # classes, imports, and relationships.
        try:
            source = file_path.read_bytes()
            if language == "python":
                parse_result = py_parser.parse(source, file_path)
            else:
                # TypeScript, TSX, JavaScript all use the TypeScript parser
                parse_result = ts_parser.parse(source, file_path)
        except Exception:
            # Corrupt or unreadable file — skip silently (already logged by orchestrator)
            continue
        parse_results.append(parse_result)
        file_count += 1

    parse_elapsed = time.monotonic() - t0
    print(f"  Parsed {file_count} file(s) in {parse_elapsed:.1f}s")

    # ------------------------------------------------------------------
    # Step 6 — Detect git HEAD for provenance stamping (optional)
    # ------------------------------------------------------------------
    git_head = _get_git_head(repo_path)

    # ------------------------------------------------------------------
    # Step 7 — Build the knowledge graph (concepts + edges)
    # ------------------------------------------------------------------
    builder = GraphBuilder(store=store, git_head=git_head)
    build_result = builder.build(parse_results)

    print(
        f"  Graph: {build_result.concepts_created} concept(s) created, "
        f"{build_result.concepts_updated} updated, "
        f"{build_result.edges_created} edge(s) created"
    )

    # ------------------------------------------------------------------
    # Step 8 — Generate embeddings (unless --no-embed is passed)
    # ------------------------------------------------------------------
    no_embed = getattr(args, "no_embed", False)
    if not no_embed and (build_result.concepts_created + build_result.concepts_updated) > 0:
        from apriori.embedding.service import EmbeddingService

        print("  Loading embedding model (first run downloads ~440MB, cached after)…")
        svc = EmbeddingService()
        svc.embed_all(store)

    # ------------------------------------------------------------------
    # Step 9 — Print final summary
    # ------------------------------------------------------------------
    total_concepts = len(store.list_concepts())
    total_edges = len(store.list_edges())
    total_elapsed = time.monotonic() - t0

    print()
    if is_incremental:
        print("A-Priori incremental update complete.")
    else:
        print("A-Priori initialisation complete.")
    print(f"  Total concepts: {total_concepts}")
    print(f"  Total edges:    {total_edges}")
    print(f"  Elapsed:        {total_elapsed:.1f}s (excluding model download)")
    print()
    print("Next steps:")
    print("  apriori search '<query>'   — search the knowledge graph")
    print("  apriori status             — view graph health metrics")
    print("  apriori ui                 — start the Graph API server")


def _get_git_head(repo_path: Path) -> str | None:
    """Return the current git HEAD SHA, or None if not a git repo."""
    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(repo_path),
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# Helpers shared by search/status commands
# ---------------------------------------------------------------------------


def _resolve_db_path(args: argparse.Namespace) -> Path:
    """Determine the SQLite database path from args, config, or defaults.

    Resolution order:
    1. Explicit ``--db`` argument.
    2. Config file found at ``.apriori/apriori.config.yaml``.
    3. Fallback: ``.apriori/graph.db``.
    """
    if args.db:
        return Path(args.db)

    from apriori.config import load_config

    apriori_config = Path.cwd() / ".apriori" / "apriori.config.yaml"
    if apriori_config.exists():
        config = load_config(apriori_config)
    else:
        config = load_config()
    return Path(config.storage.sqlite_path)


# ---------------------------------------------------------------------------
# search command
# ---------------------------------------------------------------------------


def _cmd_search(args: argparse.Namespace) -> None:
    """Search the knowledge graph using FTS keyword matching."""
    import json as _json

    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)
    query = args.query
    limit = getattr(args, "limit", 10)
    use_json = getattr(args, "json", False)

    results = store.search_keyword(query, limit=limit)

    if use_json:
        output = [
            {
                "name": c.name,
                "description": c.description,
                "confidence": c.confidence,
                "labels": sorted(c.labels),
            }
            for c in results
        ]
        print(_json.dumps(output))
        return

    if not results:
        print(f"No results for '{query}'.")
        return

    print(f"Results for '{query}' ({len(results)} match(es)):\n")
    for i, concept in enumerate(results, start=1):
        desc = concept.description or ""
        if len(desc) > 100:
            desc = desc[:97] + "…"
        print(f"  {i}. {concept.name}  conf: {concept.confidence:.2f}")
        if desc:
            print(f"     {desc}")
    print()


# ---------------------------------------------------------------------------
# status command
# ---------------------------------------------------------------------------


def _cmd_status(args: argparse.Namespace) -> None:
    """Report knowledge graph health metrics."""
    import json as _json

    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)
    use_json = getattr(args, "json", False)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)

    metrics = store.get_metrics()
    concept_count = metrics["concept_count"]
    edge_count = metrics["edge_count"]

    covered_files = store.count_covered_files()
    pending_items = store.get_pending_work_items()
    work_queue_depth = len(pending_items)

    last_parse: str | None = store.get_last_parse_timestamp()

    if use_json:
        print(_json.dumps({
            "concept_count": concept_count,
            "edge_count": edge_count,
            "covered_files": covered_files,
            "work_queue_depth": work_queue_depth,
            "last_parse": last_parse,
            "database": str(db_path.resolve()),
        }))
        return

    print("A-Priori Graph Status")
    print("=" * 40)
    print(f"  Concepts:          {concept_count}")
    print(f"  Edges:             {edge_count}")
    print(f"  Covered files:     {covered_files}")
    print(f"  Work queue depth:  {work_queue_depth}")
    print(f"  Last parse:        {last_parse or 'n/a'}")
    print(f"  Database:          {db_path.resolve()}")
    print()


# ---------------------------------------------------------------------------
# rebuild-index command
# ---------------------------------------------------------------------------


def _cmd_rebuild_index(args: argparse.Namespace) -> None:
    """Reconstruct the SQLite database from YAML flat files (arch:core-lib-thin-shells)."""
    from apriori.config import load_config
    from apriori.embedding.service import EmbeddingService
    from apriori.storage.rebuild import rebuild_index_from_yaml
    from apriori.storage.yaml_store import YamlStore

    apriori_config_path = Path.cwd() / ".apriori" / "apriori.config.yaml"
    config = load_config(apriori_config_path if apriori_config_path.exists() else None)

    db_path = Path(args.db) if getattr(args, "db", None) else Path(config.storage.sqlite_path)
    yaml_base = Path(args.yaml_path) if getattr(args, "yaml_path", None) else Path(config.storage.yaml_backup_path)

    yaml_store = YamlStore(yaml_base)

    no_embed = getattr(args, "no_embed", False)

    print(f"Rebuilding index from YAML files at {yaml_base}…")
    print(f"  Target database: {db_path.resolve()}")

    if no_embed:
        class _NullEmbeddingService:
            def generate_embedding(self, text: str, **kw: object) -> list[float]:
                return [0.0] * 768

            def generate_embeddings_batch(self, texts: list[str], **kw: object) -> list[list[float]]:
                return [[0.0] * 768 for _ in texts]

        embedding_svc: object = _NullEmbeddingService()
    else:
        print("  Loading embedding model…")
        embedding_svc = EmbeddingService()

    def _progress(current: int, total: int, message: str) -> None:
        if total > 0:
            print(f"  [{current}/{total}] {message}")
        else:
            print(f"  {message}")

    rebuild_index_from_yaml(
        yaml_store,
        db_path=db_path,
        embedding_service=embedding_svc,
        progress_callback=_progress,
    )

    print()
    print("Rebuild complete.")


# ---------------------------------------------------------------------------
# config command
# ---------------------------------------------------------------------------


def _resolve_config_path() -> Path:
    """Return the config file path, preferring .apriori/ in the current directory."""
    candidate = Path.cwd() / ".apriori" / "apriori.config.yaml"
    if candidate.exists():
        return candidate
    return candidate  # Return even if not existing so callers can create it


def _cmd_config(args: argparse.Namespace) -> None:
    """Show or modify A-Priori configuration (arch:core-lib-thin-shells)."""
    import json as _json

    from apriori.config import load_config

    config_subcommand = getattr(args, "config_subcommand", None)
    use_json = getattr(args, "json", False)

    if config_subcommand == "set":
        _config_set(args)
        return

    # Default: print effective configuration
    config_path = _resolve_config_path()
    config = load_config(config_path if config_path.exists() else None)

    if use_json:
        print(_json.dumps(config.model_dump(mode="json"), indent=2, default=str))
        return

    print(f"A-Priori Configuration  (source: {config_path})")
    print("=" * 50)
    data = config.model_dump(mode="json")
    _print_config_section(data, indent=0)
    print()


def _print_config_section(data: dict, indent: int) -> None:
    """Recursively print config dict in aligned text format."""
    prefix = "  " * indent
    for key, value in sorted(data.items()):
        if isinstance(value, dict):
            print(f"{prefix}{key}:")
            _print_config_section(value, indent + 1)
        elif isinstance(value, (list, set)):
            display = ", ".join(str(v) for v in sorted(str(x) for x in value))
            print(f"{prefix}{key}: [{display}]")
        else:
            print(f"{prefix}{key}: {value}")


def _config_set(args: argparse.Namespace) -> None:
    """Update a single key in the config file using dotted notation."""
    import yaml as _yaml

    key: str = args.key
    raw_value: str = args.value

    config_path = _resolve_config_path()

    # Load existing raw YAML (preserve structure; don't parse through Config)
    existing: dict = {}
    if config_path.exists():
        loaded = _yaml.safe_load(config_path.read_text())
        if loaded:
            existing = loaded

    # Parse the dotted key into nested path
    parts = key.split(".")
    # Navigate to the nested position, creating dicts as needed
    node = existing
    for part in parts[:-1]:
        if part not in node or not isinstance(node[part], dict):
            node[part] = {}
        node = node[part]

    leaf_key = parts[-1]
    # Coerce value type: try int, then float, then bool, then string
    coerced: object = raw_value
    if raw_value.lower() in ("true", "false"):
        coerced = raw_value.lower() == "true"
    else:
        try:
            coerced = int(raw_value)
        except ValueError:
            try:
                coerced = float(raw_value)
            except ValueError:
                coerced = raw_value  # Keep as string

    node[leaf_key] = coerced

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_yaml.dump(existing, allow_unicode=True, sort_keys=True))
    print(f"Updated {key} = {coerced!r}  (saved to {config_path})")


# ---------------------------------------------------------------------------
# ui command
# ---------------------------------------------------------------------------


def _cmd_ui(args: argparse.Namespace) -> None:
    """Start the read-only Graph API server."""
    try:
        import uvicorn
    except ImportError:
        print(
            "Error: uvicorn is required to run the UI server.\n"
            "Install it with: pip install uvicorn",
            file=sys.stderr,
        )
        sys.exit(1)

    from apriori.config import load_config
    from apriori.shells.ui.server import create_app
    from apriori.storage.dual_writer import DualWriter
    from apriori.storage.sqlite_store import SQLiteStore
    from apriori.storage.yaml_store import YamlStore

    config = load_config()

    db_path = Path(args.db) if args.db else Path(config.storage.sqlite_path)
    yaml_path = Path(config.storage.yaml_backup_path)

    sqlite_store = SQLiteStore(db_path)
    if config.storage.enable_dual_write:
        yaml_store = YamlStore(yaml_path)
        store = DualWriter(sqlite_store=sqlite_store, yaml_store=yaml_store)
    else:
        store = sqlite_store  # type: ignore[assignment]

    app = create_app(store, config)

    print(f"Starting A-Priori UI server on http://{args.host}:{args.port}")
    print(f"Database: {db_path.resolve()}")
    print("API docs: http://{}:{}/docs".format(args.host, args.port))

    uvicorn.run(app, host=args.host, port=args.port, reload=args.reload)


# ---------------------------------------------------------------------------
# blast-radius command
# ---------------------------------------------------------------------------


def _cmd_blast_radius(args: argparse.Namespace) -> None:
    """Display the pre-computed blast-radius impact profile for a target."""
    import json as _json

    from apriori.retrieval.blast_radius_query import query_blast_radius
    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)
    use_json = getattr(args, "json", False)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)
    target = args.target
    max_depth = getattr(args, "depth", None)
    min_confidence = getattr(args, "min_confidence", None)

    entries = query_blast_radius(store, target, max_depth=max_depth, min_confidence=min_confidence)

    if use_json:
        print(_json.dumps(
            [
                {
                    "concept_id": str(e.concept_id),
                    "concept_name": e.concept_name,
                    "confidence": e.confidence,
                    "impact_layer": e.impact_layer,
                    "depth": e.depth,
                    "relationship_path": e.relationship_path,
                    "rationale": e.rationale,
                    "composite_score": e.composite_score,
                }
                for e in entries
            ]
        ))
        return

    if not entries:
        print(f"No blast-radius impact found for '{target}'.")
        return

    print(f"Blast-radius impact for '{target}' ({len(entries)} entry/entries):\n")
    for i, entry in enumerate(entries, start=1):
        print(
            f"  {i}. {entry.concept_name}"
            f"  layer={entry.impact_layer}"
            f"  depth={entry.depth}"
            f"  confidence={entry.confidence:.2f}"
            f"  score={entry.composite_score:.3f}"
        )
        print(f"     {entry.rationale}")
    print()


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def _build_parser() -> argparse.ArgumentParser:
    """Build and return the top-level argument parser for the apriori CLI."""
    parser = argparse.ArgumentParser(
        prog="apriori",
        description="A-Priori knowledge graph system",
    )
    subparsers = parser.add_subparsers(dest="command", metavar="COMMAND")

    # apriori init
    init_parser = subparsers.add_parser(
        "init",
        help="Initialise A-Priori for the current repository",
    )
    init_parser.add_argument(
        "--repo",
        default=None,
        metavar="PATH",
        help="Path to the repository root (default: current directory)",
    )
    init_parser.add_argument(
        "--no-embed",
        action="store_true",
        dest="no_embed",
        help="Skip embedding generation (faster, but semantic search will not work)",
    )

    # apriori search
    search_parser = subparsers.add_parser(
        "search",
        help="Search the knowledge graph",
    )
    search_parser.add_argument(
        "query",
        help="Search query",
    )
    search_parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Maximum number of results to return (default: 10)",
    )
    search_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    search_parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON",
    )

    # apriori status
    status_parser = subparsers.add_parser(
        "status",
        help="Show knowledge graph health metrics",
    )
    status_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    status_parser.add_argument(
        "--json",
        action="store_true",
        help="Output status as JSON",
    )

    # apriori rebuild-index
    rebuild_parser = subparsers.add_parser(
        "rebuild-index",
        help="Reconstruct the SQLite database from YAML flat files",
    )
    rebuild_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database to rebuild (default: from config or .apriori/graph.db)",
    )
    rebuild_parser.add_argument(
        "--yaml-path",
        default=None,
        metavar="PATH",
        dest="yaml_path",
        help="Path to YAML backup directory (default: from config or .apriori/concepts)",
    )
    rebuild_parser.add_argument(
        "--no-embed",
        action="store_true",
        dest="no_embed",
        help="Skip embedding regeneration (uses zero vectors)",
    )

    # apriori config
    config_parser = subparsers.add_parser(
        "config",
        help="View or modify A-Priori configuration",
    )
    config_parser.add_argument(
        "--json",
        action="store_true",
        help="Output configuration as JSON",
    )
    config_subparsers = config_parser.add_subparsers(
        dest="config_subcommand", metavar="SUBCOMMAND"
    )
    config_set_parser = config_subparsers.add_parser(
        "set",
        help="Set a configuration value (dotted key notation, e.g. librarian.max_iterations_per_run)",
    )
    config_set_parser.add_argument("key", help="Dotted key path (e.g. librarian.max_iterations_per_run)")
    config_set_parser.add_argument("value", help="New value")

    # apriori ui
    ui_parser = subparsers.add_parser(
        "ui",
        help="Start the read-only Graph API and dashboard server",
    )
    ui_parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="Host to bind the server to (default: 127.0.0.1)",
    )
    ui_parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to bind the server to (default: 8000)",
    )
    ui_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or ./apriori.db)",
    )
    ui_parser.add_argument(
        "--reload",
        action="store_true",
        help="Enable auto-reload on code changes (development only)",
    )

    # apriori blast-radius
    br_parser = subparsers.add_parser(
        "blast-radius",
        help="Show the pre-computed blast-radius impact profile for a target",
    )
    br_parser.add_argument(
        "target",
        help="Concept name, UUID, file path, or function symbol to query",
    )
    br_parser.add_argument(
        "--depth",
        type=int,
        default=None,
        metavar="N",
        help="Maximum hop depth to include (default: no limit)",
    )
    br_parser.add_argument(
        "--min-confidence",
        type=float,
        default=None,
        dest="min_confidence",
        metavar="FLOAT",
        help="Minimum confidence threshold (default: no limit)",
    )
    br_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )
    br_parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON",
    )

    return parser


def main() -> None:
    """Main CLI entry point for the ``apriori`` command."""
    parser = _build_parser()
    args = parser.parse_args()

    if args.command == "init":
        _cmd_init(args)
    elif args.command == "search":
        _cmd_search(args)
    elif args.command == "status":
        _cmd_status(args)
    elif args.command == "rebuild-index":
        _cmd_rebuild_index(args)
    elif args.command == "config":
        _cmd_config(args)
    elif args.command == "ui":
        _cmd_ui(args)
    elif args.command == "blast-radius":
        _cmd_blast_radius(args)
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
