"""A-Priori CLI entry point (arch:core-lib-thin-shells).

Usage::

    apriori init [--repo PATH] [--no-embed]
    apriori search QUERY [--limit N] [--db PATH]
    apriori status [--db PATH]
    apriori ui [--host HOST] [--port PORT] [--db PATH] [--reload]

The ``init`` command initialises a repository for A-Priori:
  1. Creates ``.apriori/`` directory structure
  2. Writes a default ``apriori.config.yaml``
  3. Initialises DualWriter (SQLite + YAML)
  4. Runs the structural parser over all Python/TypeScript/JavaScript files
  5. Builds the knowledge graph (concept nodes + structural edges)
  6. Generates embeddings (unless ``--no-embed`` is passed)
  7. Prints a summary of what was discovered

The ``search`` subcommand queries the knowledge graph using FTS keyword search.
The ``status`` subcommand reports graph health metrics.
The ``ui`` subcommand launches the FastAPI server.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

# ---------------------------------------------------------------------------
# Default config template written on first init
# ---------------------------------------------------------------------------

_DEFAULT_CONFIG_TEMPLATE = """\
# A-Priori configuration — generated by `apriori init`
# Edit this file to customise your knowledge graph settings.
# Full schema: https://a-priori.dev/docs/configuration

storage:
  sqlite_path: "{apriori_dir}/graph.db"
  yaml_backup_path: "{apriori_dir}/concepts"
  enable_dual_write: true

embedding:
  model: "intfloat/e5-base-v2"
  dimensions: 768
  batch_size: 32

log_level: "INFO"
"""


# ---------------------------------------------------------------------------
# init command
# ---------------------------------------------------------------------------


def _cmd_init(args: argparse.Namespace) -> None:
    """Initialise A-Priori for a repository (thin shell, arch:core-lib-thin-shells)."""
    repo_path = Path(args.repo).resolve() if args.repo else Path.cwd().resolve()
    apriori_dir = repo_path / ".apriori"
    config_path = apriori_dir / "apriori.config.yaml"

    is_incremental = apriori_dir.exists()

    if is_incremental:
        print(f"A-Priori: incremental update for {repo_path}")
    else:
        print(f"A-Priori: initialising repository at {repo_path}")

    # ------------------------------------------------------------------
    # Step 1 — Create .apriori/ directory structure
    # ------------------------------------------------------------------
    apriori_dir.mkdir(parents=True, exist_ok=True)
    (apriori_dir / "concepts").mkdir(exist_ok=True)

    # ------------------------------------------------------------------
    # Step 2 — Write default config (only on first init)
    # ------------------------------------------------------------------
    if not is_incremental:
        config_content = _DEFAULT_CONFIG_TEMPLATE.format(
            apriori_dir=str(apriori_dir)
        )
        config_path.write_text(config_content)
        print(f"  Written config: {config_path}")

    # ------------------------------------------------------------------
    # Step 3 — Load config (reads the file we just created or an existing one)
    # ------------------------------------------------------------------
    from apriori.config import load_config

    config = load_config(config_path)

    # ------------------------------------------------------------------
    # Step 4 — Initialise storage (SQLite + YAML via DualWriter)
    # ------------------------------------------------------------------
    from apriori.storage.dual_writer import DualWriter
    from apriori.storage.sqlite_store import SQLiteStore
    from apriori.storage.yaml_store import YamlStore

    db_path = Path(config.storage.sqlite_path)
    yaml_path = Path(config.storage.yaml_backup_path)

    db_path.parent.mkdir(parents=True, exist_ok=True)
    yaml_path.mkdir(parents=True, exist_ok=True)

    sqlite_store = SQLiteStore(db_path)
    yaml_store = YamlStore(yaml_path)
    store = DualWriter(sqlite_store=sqlite_store, yaml_store=yaml_store)

    # ------------------------------------------------------------------
    # Step 5 — Run structural parser over the repository
    # ------------------------------------------------------------------
    from apriori.structural.graph_builder import GraphBuilder
    from apriori.structural.languages.python_parser import PythonParser
    from apriori.structural.languages.typescript import TypeScriptParser
    from apriori.structural.models import ParseResult
    from apriori.structural.orchestrator import Orchestrator

    print(f"  Scanning {repo_path} for source files…")
    t0 = time.monotonic()

    orchestrator = Orchestrator()
    py_parser = PythonParser()
    ts_parser = TypeScriptParser()
    parse_results: list[ParseResult] = []
    file_count = 0

    for file_path, language, _raw_result in orchestrator.walk_and_parse(repo_path):
        # The Orchestrator returns raw tree-sitter results without extracted
        # entities.  Run the language-specific parser to populate functions,
        # classes, imports, and relationships.
        try:
            source = file_path.read_bytes()
            if language == "python":
                parse_result = py_parser.parse(source, file_path)
            else:
                # TypeScript, TSX, JavaScript all use the TypeScript parser
                parse_result = ts_parser.parse(source, file_path)
        except Exception:
            # Corrupt or unreadable file — skip silently (already logged by orchestrator)
            continue
        parse_results.append(parse_result)
        file_count += 1

    parse_elapsed = time.monotonic() - t0
    print(f"  Parsed {file_count} file(s) in {parse_elapsed:.1f}s")

    # ------------------------------------------------------------------
    # Step 6 — Detect git HEAD for provenance stamping (optional)
    # ------------------------------------------------------------------
    git_head = _get_git_head(repo_path)

    # ------------------------------------------------------------------
    # Step 7 — Build the knowledge graph (concepts + edges)
    # ------------------------------------------------------------------
    builder = GraphBuilder(store=store, git_head=git_head)
    build_result = builder.build(parse_results)

    print(
        f"  Graph: {build_result.concepts_created} concept(s) created, "
        f"{build_result.concepts_updated} updated, "
        f"{build_result.edges_created} edge(s) created"
    )

    # ------------------------------------------------------------------
    # Step 8 — Generate embeddings (unless --no-embed is passed)
    # ------------------------------------------------------------------
    no_embed = getattr(args, "no_embed", False)
    if not no_embed and (build_result.concepts_created + build_result.concepts_updated) > 0:
        from apriori.embedding.service import EmbeddingService

        print("  Loading embedding model (first run downloads ~440MB, cached after)…")
        svc = EmbeddingService()
        svc.embed_all(store)

    # ------------------------------------------------------------------
    # Step 9 — Print final summary
    # ------------------------------------------------------------------
    total_concepts = len(store.list_concepts())
    total_edges = len(store.list_edges())
    total_elapsed = time.monotonic() - t0

    print()
    if is_incremental:
        print("A-Priori incremental update complete.")
    else:
        print("A-Priori initialisation complete.")
    print(f"  Total concepts: {total_concepts}")
    print(f"  Total edges:    {total_edges}")
    print(f"  Elapsed:        {total_elapsed:.1f}s (excluding model download)")
    print()
    print("Next steps:")
    print("  apriori search '<query>'   — search the knowledge graph")
    print("  apriori status             — view graph health metrics")
    print("  apriori ui                 — start the Graph API server")


def _get_git_head(repo_path: Path) -> str | None:
    """Return the current git HEAD SHA, or None if not a git repo."""
    try:
        import subprocess

        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(repo_path),
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# Helpers shared by search/status commands
# ---------------------------------------------------------------------------


def _resolve_db_path(args: argparse.Namespace) -> Path:
    """Determine the SQLite database path from args, config, or defaults.

    Resolution order:
    1. Explicit ``--db`` argument.
    2. Config file found at ``.apriori/apriori.config.yaml``.
    3. Fallback: ``.apriori/graph.db``.
    """
    if args.db:
        return Path(args.db)

    from apriori.config import load_config

    apriori_config = Path.cwd() / ".apriori" / "apriori.config.yaml"
    if apriori_config.exists():
        config = load_config(apriori_config)
    else:
        config = load_config()
    return Path(config.storage.sqlite_path)


# ---------------------------------------------------------------------------
# search command
# ---------------------------------------------------------------------------


def _cmd_search(args: argparse.Namespace) -> None:
    """Search the knowledge graph using FTS keyword matching."""
    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)
    query = args.query
    limit = getattr(args, "limit", 10)

    results = store.search_keyword(query, limit=limit)

    if not results:
        print(f"No results for '{query}'.")
        return

    print(f"Results for '{query}' ({len(results)} match(es)):\n")
    for i, concept in enumerate(results, start=1):
        print(f"  {i}. {concept.name}")
        if concept.description:
            # Truncate long descriptions
            desc = concept.description
            if len(desc) > 100:
                desc = desc[:97] + "…"
            print(f"     {desc}")
    print()


# ---------------------------------------------------------------------------
# status command
# ---------------------------------------------------------------------------


def _cmd_status(args: argparse.Namespace) -> None:
    """Report knowledge graph health metrics."""
    from apriori.storage.sqlite_store import SQLiteStore

    db_path = _resolve_db_path(args)

    if not db_path.exists():
        print(
            f"Error: database not found at {db_path}\n"
            "Run `apriori init` to initialise the knowledge graph.",
            file=sys.stderr,
        )
        sys.exit(1)

    store = SQLiteStore(db_path)

    concepts = store.list_concepts()
    edges = store.list_edges()

    concept_count = len(concepts)
    edge_count = len(edges)

    # Count concepts by label presence
    needs_review = sum(1 for c in concepts if "needs-review" in (c.labels or []))

    print("A-Priori Graph Status")
    print("=" * 40)
    print(f"  Concepts:      {concept_count}")
    print(f"  Edges:         {edge_count}")
    print(f"  Needs review:  {needs_review}")
    print(f"  Database:      {db_path.resolve()}")
    print()


# ---------------------------------------------------------------------------
# ui command
# ---------------------------------------------------------------------------


def _cmd_ui(args: argparse.Namespace) -> None:
    """Start the read-only Graph API server."""
    try:
        import uvicorn
    except ImportError:
        print(
            "Error: uvicorn is required to run the UI server.\n"
            "Install it with: pip install uvicorn",
            file=sys.stderr,
        )
        sys.exit(1)

    from apriori.config import load_config
    from apriori.shells.ui.server import create_app
    from apriori.storage.dual_writer import DualWriter
    from apriori.storage.sqlite_store import SQLiteStore
    from apriori.storage.yaml_store import YamlStore

    config = load_config()

    db_path = Path(args.db) if args.db else Path(config.storage.sqlite_path)
    yaml_path = Path(config.storage.yaml_backup_path)

    sqlite_store = SQLiteStore(db_path)
    if config.storage.enable_dual_write:
        yaml_store = YamlStore(yaml_path)
        store = DualWriter(sqlite_store=sqlite_store, yaml_store=yaml_store)
    else:
        store = sqlite_store  # type: ignore[assignment]

    app = create_app(store, config)

    print(f"Starting A-Priori UI server on http://{args.host}:{args.port}")
    print(f"Database: {db_path.resolve()}")
    print("API docs: http://{}:{}/docs".format(args.host, args.port))

    uvicorn.run(app, host=args.host, port=args.port, reload=args.reload)


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------


def main() -> None:
    """Main CLI entry point for the ``apriori`` command."""
    parser = argparse.ArgumentParser(
        prog="apriori",
        description="A-Priori knowledge graph system",
    )
    subparsers = parser.add_subparsers(dest="command", metavar="COMMAND")

    # apriori init
    init_parser = subparsers.add_parser(
        "init",
        help="Initialise A-Priori for the current repository",
    )
    init_parser.add_argument(
        "--repo",
        default=None,
        metavar="PATH",
        help="Path to the repository root (default: current directory)",
    )
    init_parser.add_argument(
        "--no-embed",
        action="store_true",
        dest="no_embed",
        help="Skip embedding generation (faster, but semantic search will not work)",
    )

    # apriori search
    search_parser = subparsers.add_parser(
        "search",
        help="Search the knowledge graph",
    )
    search_parser.add_argument(
        "query",
        help="Search query",
    )
    search_parser.add_argument(
        "--limit",
        type=int,
        default=10,
        help="Maximum number of results to return (default: 10)",
    )
    search_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )

    # apriori status
    status_parser = subparsers.add_parser(
        "status",
        help="Show knowledge graph health metrics",
    )
    status_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or .apriori/graph.db)",
    )

    # apriori ui
    ui_parser = subparsers.add_parser(
        "ui",
        help="Start the read-only Graph API and dashboard server",
    )
    ui_parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="Host to bind the server to (default: 127.0.0.1)",
    )
    ui_parser.add_argument(
        "--port",
        type=int,
        default=8000,
        help="Port to bind the server to (default: 8000)",
    )
    ui_parser.add_argument(
        "--db",
        default=None,
        metavar="PATH",
        help="Path to SQLite database (default: from config or ./apriori.db)",
    )
    ui_parser.add_argument(
        "--reload",
        action="store_true",
        help="Enable auto-reload on code changes (development only)",
    )

    args = parser.parse_args()

    if args.command == "init":
        _cmd_init(args)
    elif args.command == "search":
        _cmd_search(args)
    elif args.command == "status":
        _cmd_status(args)
    elif args.command == "ui":
        _cmd_ui(args)
    else:
        parser.print_help()
        sys.exit(0)


if __name__ == "__main__":
    main()
